name: PR build

on: pull_request

jobs:
  pr-checks:
    name: "pr-checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: touch local props
        run: touch demo-app/local.properties
      - name: run gradle
        run: ./gradlew check
      - name: build demo app
        working-directory: ./demo-app
        run: ./gradlew check assemble
      - name: Enable KVM for Android tests
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  required-status-check:
    needs:
      - pr-checks
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.pr-checks.result != 'success'
        run: exit 1